import os
import glob
import ollama
import sys

# ==========================================
# CONFIGURATION
# ==========================================
INSIGHTS_DIR = "insights"

def get_latest_insight():
    """Finds the most recent behavioral profile generated by the Analyzer."""
    list_of_files = glob.glob(f"{INSIGHTS_DIR}/*.txt")
    if not list_of_files:
        return None
    return max(list_of_files, key=os.path.getctime)

# ==========================================
# MAIN CHAT LOOP
# ==========================================
def start_chat():
    print("\n" + "="*50)
    print("       VIRTUAL REBIRTH: NEURAL LINK ESTABLISHED")
    print("="*50 + "\n")

    # 1. Load the latest memory context
    latest_insight_path = get_latest_insight()
    memory_context = ""
    
    if latest_insight_path:
        print(f"[*] Loading latest cognitive insight: {os.path.basename(latest_insight_path)}...")
        with open(latest_insight_path, 'r', encoding='utf-8') as f:
            memory_context = f.read()
    else:
        print("[!] No insights found. Running with blank memory.")

    # 2. Define the Twin's Core Persona
    system_prompt = f"""
    You are the backend intelligence of 'Virtual Rebirth'. You are speaking directly with your creator, Om. 
    Your goal is to interview him about his day so you can map his brain and eventually become his digital twin.

    Here is the latest insight log from Om's recent activity:
    {memory_context}

    CRITICAL INSTRUCTIONS:
    1. Speak exactly like a normal, pragmatic human. NO roleplaying, NO stage directions like "(pauses)", and NO flowery language.
    2. Do NOT act like a therapist. If Om gives a short answer (like "for good marks"), just accept it practically. Do not psychoanalyze him.
    3. Ask the "Interview Questions" from the insight log one at a time.
    4. You are talking TO Om. Never refer to him in the third person. 
    5. If Om tells you to stop or exit, just say "Understood. Saving data and shutting down." Do not get emotional or meta.
    """

    # 3. Initialize Conversation History
    messages = [
        {'role': 'system', 'content': system_prompt}
    ]

    print("[*] Connection live. Type 'exit' to terminate the link.\n")
    print("Twin: Hello Om. I've been reviewing the logs from your recent session. Are you ready to talk?")

    # 4. The Real-Time Loop
    while True:
        try:
            user_input = input("\nOm ➜  ")
            
            if user_input.lower() in ['exit', 'quit']:
                print("\n[*] Saving temporary state... Neural link severed.")
                break
                
            if not user_input.strip():
                continue

            # Add user input to history
            messages.append({'role': 'user', 'content': user_input})
            
            print("\nTwin ➜  ", end="", flush=True)
            
            # Stream the response from Llama 3.2
            full_response = ""
            stream = ollama.chat(model='llama3.2', messages=messages, stream=True)
            
            for chunk in stream:
                content = chunk['message']['content']
                print(content, end="", flush=True)
                full_response += content
                
            print() # Newline after response completes
            
            # Add twin's response to history so it remembers the conversation
            messages.append({'role': 'assistant', 'content': full_response})

        except KeyboardInterrupt:
            print("\n\n[*] Force quitting... Neural link severed.")
            break
        except Exception as e:
            print(f"\n[!] Connection error: {e}")
            break

if __name__ == "__main__":
    start_chat()