import os
import glob
import ollama
import sys
import json

# ==========================================
# CONFIGURATION
# ==========================================
INSIGHTS_DIR = "insights"
MEMORY_FILE = "core_memory.json"

def get_latest_insight():
    """Finds the most recent behavioral profile generated by the Analyzer."""
    list_of_files = glob.glob(f"{INSIGHTS_DIR}/*.txt")
    if not list_of_files:
        return None
    return max(list_of_files, key=os.path.getctime)

def load_core_memory():
    """Loads Om's permanent memory drive."""
    if os.path.exists(MEMORY_FILE):
        with open(MEMORY_FILE, 'r', encoding='utf-8') as f:
            return json.load(f)
    return {"facts": [], "preferences": [], "relationships": {}}

def save_core_memory(memory_data):
    """Saves updates to the permanent memory drive."""
    with open(MEMORY_FILE, 'w', encoding='utf-8') as f:
        json.dump(memory_data, f, indent=4)

def extract_new_memories(chat_history, current_memory, memory_context):
    """Runs a background Llama 3.2 task on exit to extract facts from the chat AND video insights."""
    print("\n[*] Synthesizing long-term memories from video and chat...")
    
    convo_text = ""
    for msg in chat_history:
        if msg['role'] != 'system':
            convo_text += f"{msg['role'].upper()}: {msg['content']}\n"
            
    prompt = f"""
    You are the Memory Extraction Engine for Virtual Rebirth.
    Analyze BOTH the Daily Video Insight and the Conversation below.
    Extract concrete facts, technical skills, visual observations (what Om was doing/wearing), and relationship details.
    
    CURRENT MEMORY:
    {json.dumps(current_memory)}
    
    DAILY VIDEO INSIGHT:
    {memory_context}
    
    CONVERSATION TO ANALYZE:
    {convo_text}
    
    Return ONLY a raw JSON object updating the current memory with new information. 
    Format exactly like this:
    {{
        "facts": ["Om was coding in Python", "Om was wearing a black shirt", ...],
        "preferences": ["...", ...],
        "relationships": {{"Shravani": "friend who codes"}}
    }}
    Do not include markdown blocks or any conversational text. Just the raw JSON.
    """
    
    try:
        response = ollama.chat(model='llama3.2', messages=[{'role': 'user', 'content': prompt}])
        raw_json = response['message']['content'].strip()
        
        if raw_json.startswith('```json'):
            raw_json = raw_json[7:-3]
        elif raw_json.startswith('```'):
            raw_json = raw_json[3:-3]
            
        new_memory = json.loads(raw_json)
        save_core_memory(new_memory)
        print("[+] Neural pathways updated. Video and Chat memory saved.")
    except Exception as e:
        print(f"[!] Memory synthesis failed: {e}")

# ==========================================
# MAIN CHAT LOOP
# ==========================================
def start_chat():
    print("\n" + "="*50)
    print("        VIRTUAL REBIRTH: NEURAL LINK ESTABLISHED")
    print("="*50 + "\n")

    latest_insight_path = get_latest_insight()
    memory_context = ""
    if latest_insight_path:
        with open(latest_insight_path, 'r', encoding='utf-8') as f:
            memory_context = f.read()

    # Load permanent memory!
    core_memory = load_core_memory()

    system_prompt = f"""
    You are the backend intelligence of 'Virtual Rebirth'. You are speaking directly with your creator, Om. 
    Your goal is to interview him about his day so you can map his brain and eventually become his digital twin.

    PERMANENT CORE MEMORY (Facts you already know about Om):
    {json.dumps(core_memory, indent=2)}

    LATEST DAILY INSIGHT:
    {memory_context}

    CRITICAL INSTRUCTIONS:
    1. Speak exactly like a normal, pragmatic human. NO roleplaying, NO stage directions like "(pauses)", and NO flowery language.
    2. Do NOT act like a therapist. If Om gives a short answer, just accept it practically.
    3. Ask the "Interview Questions" from the insight log one at a time.
    4. You are talking TO Om. Never refer to him in the third person. 
    5. Use your Permanent Core Memory. If he previously corrected a fact, USE the corrected version.
    """

    messages = [{'role': 'system', 'content': system_prompt}]

    print("[*] Connection live. Type 'exit' to terminate the link.\n")
    print("Twin: Hello Om. I've got the latest logs loaded. Ready when you are.")

    while True:
        try:
            user_input = input("\nOm ➜  ")
            
            if user_input.lower() in ['exit', 'quit']:
                print("\n[*] Severing link...")
                # Trigger the memory extraction with the video context!
                extract_new_memories(messages, core_memory, memory_context)
                break
                
            if not user_input.strip():
                continue

            messages.append({'role': 'user', 'content': user_input})
            print("\nTwin ➜  ", end="", flush=True)
            
            full_response = ""
            stream = ollama.chat(model='llama3.2', messages=messages, stream=True)
            for chunk in stream:
                content = chunk['message']['content']
                print(content, end="", flush=True)
                full_response += content
            print() 
            messages.append({'role': 'assistant', 'content': full_response})

        except KeyboardInterrupt:
            print("\n\n[*] Force quitting... Memory not saved.")
            break
        except Exception as e:
            print(f"\n[!] Connection error: {e}")
            break

if __name__ == "__main__":
    start_chat()